name: "Run in devenv"
description: "Execute a command inside the devenv container with the repo mounted"
inputs:
  run:
    description: "Command to run inside the devenv shell"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run in container
      shell: bash
      run: |
        UIDGID="$(id -u):$(id -g)"
        mkdir -p "$HOME/.cache/devenv-home"
        cat > /tmp/devenv-script.sh <<'EOF'
        ${{ inputs.run }}
        EOF
        chmod +x /tmp/devenv-script.sh

        docker run --rm \
          -u "$UIDGID" \
          -e DEVENV_HOME=/devenv-home \
          -v "${GITHUB_WORKSPACE}:/workspace" \
          -v "$HOME/.cache/devenv-home:/devenv-home" \
          -w /workspace \
          ghcr.io/cachix/devenv/devenv:latest \
          devenv shell ${{ inputs.run }}