name: "Run in devenv"
description: "Execute a command inside the devenv container with the repo mounted"
inputs:
  run:
    description: "Command to run inside the devenv shell"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run in container
      shell: bash
      run: |
        UIDGID="$(id -u):$(id -g)"
        docker run --rm \
          -u "$UIDGID" \
          -v "${GITHUB_WORKSPACE}:/workspace" \
          -w /workspace \
          ghcr.io/cachix/devenv/devenv:latest \
          devenv shell "${{ inputs.run }}"