name: PR Checks

on:
  pull_request_target:
    branches:
      - release
    types: [labeled, opened, reopened, synchronize, unlabeled]

jobs:
  require-version-bump-label:
    runs-on: ubuntu-latest
    steps:
      - name: Verify version-bump label
        id: verify
        run: |
          labels=$(jq -r '.pull_request.labels[].name // empty' "$GITHUB_EVENT_PATH")

          echo "Labels: $labels"

          if echo "$labels" | grep -Eq '^(patch|minor|major)$'; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: Post comment if invalid
        if: steps.verify.outputs.valid == 'false'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ❌ This PR is missing a required bump label.
            Please add one of: `patch`, `minor`, or `major`.
          comment-tag: bump-check
          mode: upsert

      - name: Delete comment if valid
        if: steps.verify.outputs.valid == 'true'
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: bump-check
          mode: delete

      - name: Fail if invalid
        if: steps.verify.outputs.valid == 'false'
        run: |
          echo "❌ Missing required version-bump label (patch|minor|major)" >&2

          exit 1